import type { Tour } from "@/types/database";
import type { TourFilters } from "@/lib/tours-query";
import { DEMO_OPERATOR_IDS } from "@/lib/demo-huts";

const now = "2026-04-06T00:00:00.000Z";

const demoCategoryById: Record<string, string> = {
  "demo-tour-002": "adventure",
  "demo-tour-006": "weekend",
  "demo-tour-014": "family",
};

const demoToursBase: Tour[] = [
  {
    id: "demo-tour-001",
    operator_id: DEMO_OPERATOR_IDS.summit,
    listing_company: "Summit Trails Co.",
    destination: "Hunza Valley Blossom Retreat",
    departure_city: "Lahore",
    departure_date: "2026-04-18",
    return_date: "2026-04-24",
    duration: "7 days / 6 nights",
    price: 92000,
    seats_total: 24,
    seats_remaining: 9,
    itinerary:
      "Day 1 Islamabad\nDay 2 Naran stopover\nDay 3-5 Hunza local exploration\nDay 6 Attabad & Khunjerab viewpoint\nDay 7 Return",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotel, breakfast & dinner, guided sightseeing.",
    exclusions: "Lunch, personal expenses, pony rides.",
    cancellation_policy: "70% refund up to 10 days before departure.",
    whatsapp_contact: "923001112233",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-002",
    operator_id: DEMO_OPERATOR_IDS.northbound,
    listing_company: "Northbound Escapes",
    destination: "Skardu & Deosai Adventure",
    departure_city: "Islamabad",
    departure_date: "2026-05-02",
    return_date: "2026-05-09",
    duration: "8 days / 7 nights",
    price: 108000,
    seats_total: 20,
    seats_remaining: 6,
    itinerary: "Skardu city, Shigar, Deosai National Park, Satpara and Shangrila.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotels, jeep for Deosai, breakfast.",
    exclusions: "Airfare, lunches, entry tickets.",
    cancellation_policy: "50% refund up to 7 days before departure.",
    whatsapp_contact: "923012223344",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-003",
    operator_id: DEMO_OPERATOR_IDS.greenPeak,
    listing_company: "Travelpedia Partner - Green Peak",
    destination: "Fairy Meadows Basecamp Trip",
    departure_city: "Rawalpindi",
    departure_date: "2026-05-15",
    return_date: "2026-05-21",
    duration: "7 days / 6 nights",
    price: 88000,
    seats_total: 18,
    seats_remaining: 4,
    itinerary: "Raikot bridge, jeep ride, trek to Fairy Meadows and Nanga Parbat view.",
    itinerary_pdf_path: null,
    inclusions: "Transport, jeep, lodging, breakfasts.",
    exclusions: "Trekking gear and porter charges.",
    cancellation_policy: "Non-refundable within 72 hours of departure.",
    whatsapp_contact: "923023334455",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-004",
    operator_id: DEMO_OPERATOR_IDS.riverstone,
    listing_company: "Riverstone Adventures",
    destination: "Naran Kaghan Family Escape",
    departure_city: "Lahore",
    departure_date: "2026-05-22",
    return_date: "2026-05-26",
    duration: "5 days / 4 nights",
    price: 54000,
    seats_total: 30,
    seats_remaining: 12,
    itinerary: "Naran, Saif-ul-Malook, Kaghan and river-side camps.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotel, breakfasts & dinners.",
    exclusions: "Boating and jeep add-ons.",
    cancellation_policy: "80% refund up to 5 days before departure.",
    whatsapp_contact: "923034445566",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-005",
    operator_id: DEMO_OPERATOR_IDS.baltistan,
    listing_company: "Baltistan Gateways",
    destination: "Khaplu Cultural & Forts Tour",
    departure_city: "Karachi",
    departure_date: "2026-06-03",
    return_date: "2026-06-10",
    duration: "8 days / 7 nights",
    price: 124000,
    seats_total: 16,
    seats_remaining: 5,
    itinerary: "Skardu to Khaplu forts, local villages and heritage walks.",
    itinerary_pdf_path: null,
    inclusions: "Hotel, breakfast, guided heritage visits.",
    exclusions: "Flights and personal shopping.",
    cancellation_policy: "60% refund up to 7 days before departure.",
    whatsapp_contact: "923045556677",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-006",
    operator_id: DEMO_OPERATOR_IDS.snowline,
    listing_company: "Snowline Journeys",
    destination: "Swat Kalam Mahodand Lake",
    departure_city: "Islamabad",
    departure_date: "2026-06-12",
    return_date: "2026-06-16",
    duration: "5 days / 4 nights",
    price: 49000,
    seats_total: 28,
    seats_remaining: 8,
    itinerary: "Malam Jabba, Kalam valley, Mahodand lake jeep day.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotel, breakfast, jeep transfer.",
    exclusions: "Chairlift tickets and lunches.",
    cancellation_policy: "70% refund up to 4 days before departure.",
    whatsapp_contact: "923056667788",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-007",
    operator_id: DEMO_OPERATOR_IDS.glacier,
    listing_company: "Glacier Routes",
    destination: "Astore & Rama Meadows",
    departure_city: "Rawalpindi",
    departure_date: "2026-06-20",
    return_date: "2026-06-25",
    duration: "6 days / 5 nights",
    price: 76000,
    seats_total: 22,
    seats_remaining: 11,
    itinerary: "Astore bazaar, Rama meadows camp, viewpoints and lakes.",
    itinerary_pdf_path: null,
    inclusions: "Transport, camps/hotel, meals as per plan.",
    exclusions: "Horse rides and private jeep upgrades.",
    cancellation_policy: "50% refund up to 5 days before departure.",
    whatsapp_contact: "923067778899",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-008",
    operator_id: DEMO_OPERATOR_IDS.alpineLink,
    listing_company: "Travelpedia Partner - Alpine Link",
    destination: "Neelum Valley Scenic Loop",
    departure_city: "Lahore",
    departure_date: "2026-06-28",
    return_date: "2026-07-03",
    duration: "6 days / 5 nights",
    price: 67000,
    seats_total: 26,
    seats_remaining: 7,
    itinerary: "Keran, Sharda and Arang Kel with local guided support.",
    itinerary_pdf_path: null,
    inclusions: "Transport, accommodation, breakfasts & dinners.",
    exclusions: "ATV/horse optional activities.",
    cancellation_policy: "75% refund up to 6 days before departure.",
    whatsapp_contact: "923078889900",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-009",
    operator_id: DEMO_OPERATOR_IDS.northbound,
    listing_company: "Northbound Escapes",
    destination: "Chitral & Kalash Valley",
    departure_city: "Islamabad",
    departure_date: "2026-07-08",
    return_date: "2026-07-15",
    duration: "8 days / 7 nights",
    price: 132000,
    seats_total: 14,
    seats_remaining: 3,
    itinerary: "Lower Chitral, Bumburet valley, local cultural immersion.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotels, breakfast, guide.",
    exclusions: "Festival tickets and lunches.",
    cancellation_policy: "No refund 48 hours before departure.",
    whatsapp_contact: "923089990011",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-010",
    operator_id: DEMO_OPERATOR_IDS.summit,
    listing_company: "Summit Trails Co.",
    destination: "Shogran Siri Paye Weekend",
    departure_city: "Islamabad",
    departure_date: "2026-07-18",
    return_date: "2026-07-20",
    duration: "3 days / 2 nights",
    price: 32000,
    seats_total: 32,
    seats_remaining: 15,
    itinerary: "Shogran stay, jeep to Siri Paye, nature walk and return.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotel, breakfasts.",
    exclusions: "Jeep if weather-dependent route changes.",
    cancellation_policy: "85% refund up to 3 days before departure.",
    whatsapp_contact: "923091111222",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-011",
    operator_id: DEMO_OPERATOR_IDS.northbound,
    listing_company: "Riverstone Adventures",
    destination: "Hunza + Nagar Explorer",
    departure_city: "Karachi",
    departure_date: "2026-07-25",
    return_date: "2026-08-01",
    duration: "8 days / 7 nights",
    price: 116000,
    seats_total: 20,
    seats_remaining: 10,
    itinerary: "Altit, Baltit, Hopper glacier and local food tour.",
    itinerary_pdf_path: null,
    inclusions: "Accommodation, transport, guided city and village tours.",
    exclusions: "Meals outside itinerary.",
    cancellation_policy: "60% refund up to 7 days before departure.",
    whatsapp_contact: "923092223333",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-012",
    operator_id: DEMO_OPERATOR_IDS.baltistan,
    listing_company: "Baltistan Gateways",
    destination: "Skardu Cold Desert & Lakes",
    departure_city: "Lahore",
    departure_date: "2026-08-06",
    return_date: "2026-08-12",
    duration: "7 days / 6 nights",
    price: 98000,
    seats_total: 18,
    seats_remaining: 6,
    itinerary: "Sarfaranga, Upper Kachura, blind lake and forts.",
    itinerary_pdf_path: null,
    inclusions: "Hotels, transport, breakfasts, local guide.",
    exclusions: "Boating and photography permits.",
    cancellation_policy: "65% refund up to 6 days before departure.",
    whatsapp_contact: "923093334444",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-013",
    operator_id: DEMO_OPERATOR_IDS.snowline,
    listing_company: "Snowline Journeys",
    destination: "Kumrat Valley Camping",
    departure_city: "Islamabad",
    departure_date: "2026-08-15",
    return_date: "2026-08-19",
    duration: "5 days / 4 nights",
    price: 56000,
    seats_total: 24,
    seats_remaining: 13,
    itinerary: "Jahaz Banda approach, riverside camp and guided treks.",
    itinerary_pdf_path: null,
    inclusions: "Transport, camping gear, dinner and breakfast.",
    exclusions: "Personal hiking equipment.",
    cancellation_policy: "70% refund up to 5 days before departure.",
    whatsapp_contact: "923094445555",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-014",
    operator_id: DEMO_OPERATOR_IDS.alpineArc,
    listing_company: "Alpine Arc Travels",
    destination: "Murree to Ayubia Nature Trail",
    departure_city: "Lahore",
    departure_date: "2026-08-23",
    return_date: "2026-08-25",
    duration: "3 days / 2 nights",
    price: 28000,
    seats_total: 36,
    seats_remaining: 18,
    itinerary: "Patriata, Ayubia track, local sightseeing and return.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotel, breakfast.",
    exclusions: "Chairlift and amusement tickets.",
    cancellation_policy: "80% refund up to 2 days before departure.",
    whatsapp_contact: "923095556666",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-015",
    operator_id: DEMO_OPERATOR_IDS.glacierNest,
    listing_company: "Travelpedia Partner - GlacierNest",
    destination: "Minimarg & Domel Expedition",
    departure_city: "Rawalpindi",
    departure_date: "2026-09-03",
    return_date: "2026-09-09",
    duration: "7 days / 6 nights",
    price: 119000,
    seats_total: 14,
    seats_remaining: 4,
    itinerary: "Astore, Domel, Minimarg meadows with 4x4 mobility.",
    itinerary_pdf_path: null,
    inclusions: "4x4 transport, lodging, breakfasts & dinners.",
    exclusions: "Permit fees and insurance.",
    cancellation_policy: "55% refund up to 7 days before departure.",
    whatsapp_contact: "923096667777",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-016",
    operator_id: DEMO_OPERATOR_IDS.greenPeak,
    listing_company: "Green Peak Adventures",
    destination: "Shandur Pass Road Journey",
    departure_city: "Islamabad",
    departure_date: "2026-09-14",
    return_date: "2026-09-21",
    duration: "8 days / 7 nights",
    price: 139000,
    seats_total: 12,
    seats_remaining: 5,
    itinerary: "Gilgit to Phandar and Shandur pass viewpoints.",
    itinerary_pdf_path: null,
    inclusions: "Transport, stay, guide, breakfasts.",
    exclusions: "Festival tickets and lunches.",
    cancellation_policy: "50% refund up to 7 days before departure.",
    whatsapp_contact: "923097778888",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-017",
    operator_id: DEMO_OPERATOR_IDS.alpineLink,
    listing_company: "Alpine Link",
    destination: "Babusar Top Explorer",
    departure_city: "Lahore",
    departure_date: "2026-09-26",
    return_date: "2026-09-30",
    duration: "5 days / 4 nights",
    price: 61000,
    seats_total: 26,
    seats_remaining: 9,
    itinerary: "Naran base, Babusar top, alpine landscape photography.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotel, breakfast & dinner.",
    exclusions: "Camera permits and lunches.",
    cancellation_policy: "70% refund up to 4 days before departure.",
    whatsapp_contact: "923098889999",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-018",
    operator_id: DEMO_OPERATOR_IDS.summit,
    listing_company: "Summit Trails Co.",
    destination: "Autumn Hunza Colors Tour",
    departure_city: "Karachi",
    departure_date: "2026-10-10",
    return_date: "2026-10-17",
    duration: "8 days / 7 nights",
    price: 129000,
    seats_total: 20,
    seats_remaining: 8,
    itinerary: "Hunza autumn route, Attabad, Passu and culture evening.",
    itinerary_pdf_path: null,
    inclusions: "Accommodation, transport, breakfast, local guide.",
    exclusions: "Flights and personal shopping.",
    cancellation_policy: "60% refund up to 8 days before departure.",
    whatsapp_contact: "923099990000",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-019",
    operator_id: DEMO_OPERATOR_IDS.northbound,
    listing_company: "Northbound Escapes",
    destination: "Gilgit City + Naltar Valley",
    departure_city: "Islamabad",
    departure_date: "2026-10-22",
    return_date: "2026-10-27",
    duration: "6 days / 5 nights",
    price: 83000,
    seats_total: 22,
    seats_remaining: 12,
    itinerary: "Gilgit city walk, Naltar valley jeep day and local markets.",
    itinerary_pdf_path: null,
    inclusions: "Transport, accommodation, breakfast.",
    exclusions: "Entry tickets and lunches.",
    cancellation_policy: "75% refund up to 5 days before departure.",
    whatsapp_contact: "923000001111",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-020",
    operator_id: DEMO_OPERATOR_IDS.riverstone,
    listing_company: "Riverstone Adventures",
    destination: "Patriata Weekend Escape",
    departure_city: "Rawalpindi",
    departure_date: "2026-11-07",
    return_date: "2026-11-09",
    duration: "3 days / 2 nights",
    price: 25000,
    seats_total: 40,
    seats_remaining: 21,
    itinerary: "Patriata hills, local dining and leisure stay.",
    itinerary_pdf_path: null,
    inclusions: "Transport and hotel stay.",
    exclusions: "Meals outside package.",
    cancellation_policy: "85% refund up to 48 hours before departure.",
    whatsapp_contact: "923000002222",
    status: "active",
    created_at: now,
  },
  {
    id: "demo-tour-past-001",
    operator_id: DEMO_OPERATOR_IDS.summit,
    listing_company: "Summit Trails Co.",
    destination: "Classic Hunza Autumn (completed)",
    departure_city: "Lahore",
    departure_date: "2025-10-05",
    return_date: "2025-10-12",
    duration: "8 days / 7 nights",
    price: 89500,
    seats_total: 22,
    seats_remaining: 0,
    itinerary: "Completed departure — Hunza loop with Attabad and Baltit Fort.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotel, meals as per plan.",
    exclusions: "Personal expenses.",
    cancellation_policy: "Archived listing.",
    whatsapp_contact: "923001112233",
    status: "closed",
    created_at: now,
  },
  {
    id: "demo-tour-past-002",
    operator_id: DEMO_OPERATOR_IDS.riverstone,
    listing_company: "Riverstone Adventures",
    destination: "Swat Spring Family Week (completed)",
    departure_city: "Islamabad",
    departure_date: "2025-04-10",
    return_date: "2025-04-14",
    duration: "5 days / 4 nights",
    price: 46500,
    seats_total: 28,
    seats_remaining: 0,
    itinerary: "Completed — Malam Jabba and Kalam highlights.",
    itinerary_pdf_path: null,
    inclusions: "Transport, hotel, breakfast.",
    exclusions: "Lunches.",
    cancellation_policy: "Archived listing.",
    whatsapp_contact: "923034445566",
    status: "closed",
    created_at: now,
  },
  {
    id: "demo-tour-past-003",
    operator_id: DEMO_OPERATOR_IDS.northbound,
    listing_company: "Northbound Escapes",
    destination: "Skardu Winter Preview (completed)",
    departure_city: "Karachi",
    departure_date: "2025-02-01",
    return_date: "2025-02-08",
    duration: "8 days / 7 nights",
    price: 102000,
    seats_total: 18,
    seats_remaining: 0,
    itinerary: "Completed — Skardu city, Shigar, cold desert.",
    itinerary_pdf_path: null,
    inclusions: "Flights not included; ground package only.",
    exclusions: "Airfare.",
    cancellation_policy: "Archived listing.",
    whatsapp_contact: "923012223344",
    status: "closed",
    created_at: now,
  },
];

export const demoTours: Tour[] = demoToursBase.map((t) => ({
  ...t,
  listing_category: t.listing_category ?? demoCategoryById[t.id] ?? "group_tour",
}));

function sortTours(items: Tour[], sort: "departure" | "price_asc" = "departure"): Tour[] {
  const out = [...items];
  if (sort === "price_asc") {
    out.sort((a, b) => Number(a.price) - Number(b.price));
  } else {
    out.sort(
      (a, b) =>
        new Date(a.departure_date).getTime() - new Date(b.departure_date).getTime(),
    );
  }
  return out;
}

export function getDemoTours(filters: TourFilters = {}): Tour[] {
  let out = demoTours.filter((t) => t.status === "active");

  if (filters.destination?.trim()) {
    const q = filters.destination.trim().toLowerCase();
    out = out.filter((t) => t.destination.toLowerCase().includes(q));
  }
  if (filters.from) {
    out = out.filter((t) => t.departure_date >= filters.from!);
  }
  if (filters.to) {
    out = out.filter((t) => t.departure_date <= filters.to!);
  }
  if (filters.minPrice != null && !Number.isNaN(filters.minPrice)) {
    out = out.filter((t) => Number(t.price) >= filters.minPrice!);
  }
  if (filters.maxPrice != null && !Number.isNaN(filters.maxPrice)) {
    out = out.filter((t) => Number(t.price) <= filters.maxPrice!);
  }
  if (filters.category?.trim()) {
    out = out.filter((t) => (t.listing_category ?? "group_tour") === filters.category);
  }

  return sortTours(out, filters.sort ?? "departure");
}

export function getDemoTourById(id: string): Tour | null {
  return demoTours.find((t) => t.id === id) ?? null;
}
